import os
import sys
import shutil
import time
from pathlib import Path

# Add project root to path
sys.path.append(str(Path(__file__).resolve().parent.parent))

import database
import engine

def setup_test_directories():
    base_dir = Path(__file__).resolve().parent / "test_io_modes"
    src_dir = base_dir / "src"
    dst_dir = base_dir / "dst"
    
    if base_dir.exists():
        try:
            shutil.rmtree(base_dir)
        except Exception:
            pass
        
    src_dir.mkdir(parents=True, exist_ok=True)
    dst_dir.mkdir(parents=True, exist_ok=True)
    return src_dir, dst_dir

def main():
    print("==================================================")
    print("      FileSniffer Sync Modes & Proxy Test        ")
    print("==================================================")

    # 1. Setup folders
    src_dir, dst_dir = setup_test_directories()
    
    # 2. Configure Mock Executables
    mock_oiiotool = str((Path(__file__).resolve().parent / "mock_oiiotool.bat").resolve())
    mock_ffmpeg = str((Path(__file__).resolve().parent / "mock_ffmpeg.bat").resolve())
    
    database.set_setting("oiiotool_path", mock_oiiotool)
    database.set_setting("ffmpeg_path", mock_ffmpeg)
    database.set_setting("settle_time_seconds", 1)  # 1s settle time
    database.set_setting("max_threads", 2)
    
    # Clean old jobs
    jobs = database.get_all_jobs()
    for j in jobs:
        if j['name'] == "SyncModesTestJob":
            database.delete_job(j['id'])
            
    # 3. Create job in Update mode
    job_id = database.add_job(
        name="SyncModesTestJob",
        source=str(src_dir.resolve()),
        destination=str(dst_dir.resolve()),
        schedule_type="Manual",
        schedule_value="",
        convert_enabled=0,  # Direct copy for testing file diffs
        convert_extensions="exr",
        target_compression="dwab",
        prune_enabled=0,
        prune_threshold_gb=20.0,
        proxy_enabled=1,   # proxy generation enabled
        proxy_fps=30,      # custom FPS 30
        sync_mode="update"
    )
    print(f"Created SyncModesTestJob ID: {job_id}")
    job = database.get_job(job_id)

    # Create dummy source files
    (src_dir / "seq.0001.exr").write_text("EXR frame 1 content")
    (src_dir / "seq.0002.exr").write_text("EXR frame 2 content")
    (src_dir / "seq.0003.exr").write_text("EXR frame 3 content")
    
    print("\n[Phase 1] Scanning for New Files...")
    pending = engine.scan_job_files(job)
    print(f"Found {len(pending)} files pending sync.")
    for f in pending:
        print(f"  File: {f['relative_path']} | Conflict: {f['conflict_type']} | Target Exists: {f['target_exists']}")
        assert f['conflict_type'] == 'new', f"Expected conflict type 'new', got {f['conflict_type']}"
        assert f['target_exists'] == False, "Expected target_exists to be False"

    # Wait for files to settle
    print("Waiting for files to settle (1.5 seconds)...")
    time.sleep(1.5)

    # Simulate selective transfer (user only checked seq.0001.exr and seq.0002.exr in update dialog)
    selected_files = [f for f in pending if f['relative_path'] in ("seq.0001.exr", "seq.0002.exr")]
    
    sync_done = False
    sync_success = False
    
    def on_progress(rel_path, status, bytes_tx, bytes_saved):
        print(f"  [Progress] {rel_path} -> Status: {status}")
        
    def on_finished(j_id, success, message):
        nonlocal sync_done, sync_success
        sync_done = True
        sync_success = success
        print(f"  [Finished] Job {j_id} finished. Success: {success}. Msg: {message}")

    print("\nTriggering Sync with selected subset (seq.0001.exr and seq.0002.exr)...")
    engine.sync_job(job_id, on_progress, on_finished, files_to_sync=selected_files)
    
    timeout = 10
    start_t = time.time()
    while not sync_done and (time.time() - start_t) < timeout:
        time.sleep(0.2)
        
    if not sync_done:
        print("FAIL: Sync Job timed out!", file=sys.stderr)
        sys.exit(1)

    print("\nVerifying subset transfer...")
    assert (dst_dir / "seq.0001.exr").exists(), "seq.0001.exr should have been copied"
    assert (dst_dir / "seq.0002.exr").exists(), "seq.0002.exr should have been copied"
    assert not (dst_dir / "seq.0003.exr").exists(), "seq.0003.exr should NOT have been copied"
    print("  - SUCCESS: Only checked subset of files was copied.")

    # Let's verify mock ffmpeg arguments to make sure no lutrgb is present, and proxy_fps is 30.
    log_path = Path(__file__).resolve().parent / "ffmpeg_args.log"
    assert log_path.exists(), "ffmpeg_args.log was not generated by mock ffmpeg"
    ffmpeg_args_str = log_path.read_text()
    print(f"Mock FFmpeg arguments received: {ffmpeg_args_str}")
    
    assert "lutrgb" not in ffmpeg_args_str, "FAIL: lutrgb (gamma correction) was found in ffmpeg command!"
    assert "-framerate 30" in ffmpeg_args_str, "FAIL: Expected framerate 30 in ffmpeg command!"
    print("  - SUCCESS: FFmpeg command parameters verified (no linear-to-sRGB convert, custom FPS 30).")

    # Clean up test directories
    try:
        shutil.rmtree(src_dir.parent)
    except Exception:
        pass
    if log_path.exists():
        log_path.unlink()

    print("\n==================================================")
    print("      ALL SYNC MODES AND PROXY TESTS PASSED!      ")
    print("==================================================")

if __name__ == "__main__":
    main()
